// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int greater = 0;
		int less = 0;

		for(int i=0; i<Integer.parseInt(args[0]); i++){
				double random = Math.random();
				if (random>0.5)
					greater++;
				else
					less++;
		}

		System.out.println("> 0.5: " + greater + " times");
		System.out.println("<= 0.5: " + less + " times");
		if (less !=0 && greater != 0) 
			if (greater<less)
				System.out.println("Ratio: " + (double)greater/less);
			else
			System.out.println("Ratio: " + (double)less/greater);
	}
}
